/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Banco.Banco;
import DAO.CaixaDAO;
import Model.Caixa;
import Model.Cliente;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author enzop
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuPrincipal
     */
    String nome;
    public String recebeCargo(){
        String cargo = "";
        String sql = "SELECT nome as nome, cargo as cargo from Funcionarios where logado = 1;";
        try {
            Banco.abrir();
            PreparedStatement pst = Banco.getConexao().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            cargo = rs.getString("cargo");
            nome = rs.getString("nome");
            Banco.fechar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return cargo;
    }
    CaixaDAO caixa = new CaixaDAO();
    
    int caixastats;
    
    public int recebeCaixa(){
        String sql = "SELECT count(*) as status from controlecaixa where status = 1;";
        try {
            Banco.abrir();
            PreparedStatement pst = Banco.getConexao().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            caixastats = rs.getInt("status");
            Banco.fechar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return caixastats;
    }
    
    public void atualizaLblCaixa(){
        recebeCaixa();
        if(caixastats == 1){
            lblBolinha.setText("∙");
            lblBolinha.setForeground(new Color(0,255,0));
            lblCaixa.setText("Caixa aberto");
        }else{
            lblBolinha.setText("∙");
            lblBolinha.setForeground(new Color(255,0,0));
            lblCaixa.setText("Caixa fechado");
        }
    }
    public MenuPrincipal() {
        initComponents();
        String cargo = recebeCargo();
        if(cargo.equals("atendente")){
            fecharCaixa.setEnabled(false);
        }
        lblNome.setText("Bem Vindo " + nome);
        atualizaLblCaixa();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        lblNome = new javax.swing.JLabel();
        lblCaixa = new javax.swing.JLabel();
        lblBolinha = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuCaixa = new javax.swing.JMenu();
        abrirCaixa = new javax.swing.JMenuItem();
        fecharCaixa = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        itemAddCliente = new javax.swing.JMenuItem();
        itemAltCliente = new javax.swing.JMenuItem();
        itemConsultaCliente = new javax.swing.JMenuItem();
        itemExcluirCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAddMed = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuVenda = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("jLabel2");

        lblCaixa.setForeground(new java.awt.Color(255, 255, 255));
        lblCaixa.setText("jLabel1");

        lblBolinha.setText("jLabel1");

        painelPrincipal.setLayer(lblNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelPrincipal.setLayer(lblCaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelPrincipal.setLayer(lblBolinha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblBolinha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaixa)
                    .addComponent(lblBolinha))
                .addContainerGap())
        );

        menuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cash-register-32.png"))); // NOI18N
        menuCaixa.setText("Caixa");

        abrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-open-sign-24.png"))); // NOI18N
        abrirCaixa.setText("Abrir");
        abrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCaixaActionPerformed(evt);
            }
        });
        menuCaixa.add(abrirCaixa);

        fecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-close-sign-24.png"))); // NOI18N
        fecharCaixa.setText("Fechar");
        fecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharCaixaActionPerformed(evt);
            }
        });
        menuCaixa.add(fecharCaixa);

        menuPrincipal.add(menuCaixa);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-client-management-30.png"))); // NOI18N
        menuCliente.setText("Cliente");

        itemAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-plus-24.png"))); // NOI18N
        itemAddCliente.setText("Adicionar");
        itemAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemAddCliente);

        itemAltCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-transfer-24.png"))); // NOI18N
        itemAltCliente.setText("Alterar");
        itemAltCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemAltCliente);

        itemConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-google-web-search-24.png"))); // NOI18N
        itemConsultaCliente.setText("Consultar");
        itemConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemConsultaCliente);

        itemExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancel-24.png"))); // NOI18N
        itemExcluirCliente.setText("Excluir");
        menuCliente.add(itemExcluirCliente);

        menuPrincipal.add(menuCliente);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pills-30.png"))); // NOI18N
        jMenu3.setText("Medicamentos");

        itemAddMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-plus-24.png"))); // NOI18N
        itemAddMed.setText("Adicionar");
        itemAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddMedActionPerformed(evt);
            }
        });
        jMenu3.add(itemAddMed);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-transfer-24.png"))); // NOI18N
        jMenuItem15.setText("Alterar");
        jMenu3.add(jMenuItem15);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-google-web-search-24.png"))); // NOI18N
        jMenuItem14.setText("Consultar");
        jMenu3.add(jMenuItem14);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancel-24.png"))); // NOI18N
        jMenuItem13.setText("Excluir");
        jMenu3.add(jMenuItem13);

        menuPrincipal.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sell-32.png"))); // NOI18N
        jMenu4.setText("Venda");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        MenuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sell-32.png"))); // NOI18N
        MenuVenda.setText("Venda");
        MenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVendaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuVenda);

        menuPrincipal.add(jMenu4);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        btnSair.add(Sair);

        menuPrincipal.add(btnSair);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddClienteActionPerformed
        // TODO add your handling code here:
        
        TelaCadastroCliente telaCadCliente = new TelaCadastroCliente();
        painelPrincipal.add(telaCadCliente);
        telaCadCliente.setVisible(true);
        
        
    }//GEN-LAST:event_itemAddClienteActionPerformed

    private void itemAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddMedActionPerformed
        // TODO add your handling code here:
        TelaCadastroMedicamento telaCadMedicamento = new TelaCadastroMedicamento();
        painelPrincipal.add(telaCadMedicamento);
        telaCadMedicamento.setVisible(true);
    }//GEN-LAST:event_itemAddMedActionPerformed

    private void fecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharCaixaActionPerformed
        Date horario = new Date();
        Caixa c = new Caixa(1, horario, horario, 0, 0, 0);
        try {
            Banco.abrir();
            String count = "SELECT count(*) as contador from controleCaixa where status = 1;";
            PreparedStatement pst = Banco.getConexao().prepareStatement(count);
            ResultSet rs = pst.executeQuery();
            rs.next();
            int alo = rs.getInt("contador");
            if (alo == 1){
                String resp = JOptionPane.showInputDialog(null, "Digite o valor final");
                double ola = (Double.parseDouble(resp));
                caixa.valorFinal(ola);
                caixa.inserir(c);
                atualizaLblCaixa();
                
            }else{
                JOptionPane.showMessageDialog(null, "Caixa já está fechado");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_fecharCaixaActionPerformed

    private void itemConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaClienteActionPerformed
       
    }//GEN-LAST:event_itemConsultaClienteActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void MenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVendaActionPerformed
        // TODO add your handling code here:
        TelaVenda venda;
        try {
            venda = new TelaVenda();
            venda.setVisible(true);
            dispose();
        } catch (ParseException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuVendaActionPerformed

    private void itemAltClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltClienteActionPerformed
        // TODO add your handling code here:
        AtualizarCliente telaAt = new AtualizarCliente();
        painelPrincipal.add(telaAt);
        telaAt.setVisible(true);
    }//GEN-LAST:event_itemAltClienteActionPerformed

    private void abrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCaixaActionPerformed
        Date horario = new Date();
        Caixa c = new Caixa(1, horario, horario, 0, 0, 0);
        try {
            Banco.abrir();
            String count = "SELECT count(*) as contador from controleCaixa where status = 1;";
            PreparedStatement pst = Banco.getConexao().prepareStatement(count);
            ResultSet rs = pst.executeQuery();
            rs.next();
            int alo = rs.getInt("contador");
            if (alo == 0){
                String resp = JOptionPane.showInputDialog(null, "Digite o valor inicial");
                c.setDinheiro(Double.parseDouble(resp));
                caixa.inserir(c);
                caixa.valorInicial(c);
                atualizaLblCaixa();
            }else{
                JOptionPane.showMessageDialog(null, "Caixa já está aberto");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_abrirCaixaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_OPTION){
            String sql = "update funcionarios set logado = 0";
            try{
                Banco.abrir();
                PreparedStatement pst = Banco.getConexao().prepareStatement(sql);
                pst.executeUpdate(); 
                Banco.fechar();
                this.dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuVenda;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem abrirCaixa;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenuItem fecharCaixa;
    private javax.swing.JMenuItem itemAddCliente;
    private javax.swing.JMenuItem itemAddMed;
    private javax.swing.JMenuItem itemAltCliente;
    private javax.swing.JMenuItem itemConsultaCliente;
    private javax.swing.JMenuItem itemExcluirCliente;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JLabel lblBolinha;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblNome;
    private javax.swing.JMenu menuCaixa;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
