/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Banco.Banco;
import DAO.CaixaDAO;
import Model.Caixa;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author enzop
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    CaixaDAO caixa = new CaixaDAO();
    public MenuPrincipal() {
        initComponents();
        System.out.println("ola");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuCaixa = new javax.swing.JMenu();
        abrirCaixa = new javax.swing.JMenuItem();
        fecharCaixa = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        itemAddCliente = new javax.swing.JMenuItem();
        itemAltCliente = new javax.swing.JMenuItem();
        itemConsultaCliente = new javax.swing.JMenuItem();
        itemExcluirCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAddMed = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        menuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cash-register-32.png"))); // NOI18N
        menuCaixa.setText("Caixa");

        abrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-open-sign-24.png"))); // NOI18N
        abrirCaixa.setText("Abrir");
        abrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCaixaActionPerformed(evt);
            }
        });
        menuCaixa.add(abrirCaixa);

        fecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-close-sign-24.png"))); // NOI18N
        fecharCaixa.setText("Fechar");
        fecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharCaixaActionPerformed(evt);
            }
        });
        menuCaixa.add(fecharCaixa);

        menuPrincipal.add(menuCaixa);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-client-management-30.png"))); // NOI18N
        menuCliente.setText("Cliente");

        itemAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-plus-24.png"))); // NOI18N
        itemAddCliente.setText("Adicionar");
        itemAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemAddCliente);

        itemAltCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-transfer-24.png"))); // NOI18N
        itemAltCliente.setText("Alterar");
        menuCliente.add(itemAltCliente);

        itemConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-google-web-search-24.png"))); // NOI18N
        itemConsultaCliente.setText("Consultar");
        menuCliente.add(itemConsultaCliente);

        itemExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancel-24.png"))); // NOI18N
        itemExcluirCliente.setText("Excluir");
        menuCliente.add(itemExcluirCliente);

        menuPrincipal.add(menuCliente);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pills-30.png"))); // NOI18N
        jMenu3.setText("Medicamentos");

        itemAddMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-plus-24.png"))); // NOI18N
        itemAddMed.setText("Adicionar");
        itemAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddMedActionPerformed(evt);
            }
        });
        jMenu3.add(itemAddMed);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-transfer-24.png"))); // NOI18N
        jMenuItem15.setText("Alterar");
        jMenu3.add(jMenuItem15);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-google-web-search-24.png"))); // NOI18N
        jMenuItem14.setText("Consultar");
        jMenu3.add(jMenuItem14);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancel-24.png"))); // NOI18N
        jMenuItem13.setText("Excluir");
        jMenu3.add(jMenuItem13);

        menuPrincipal.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sell-32.png"))); // NOI18N
        jMenu4.setText("Venda");
        menuPrincipal.add(jMenu4);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddClienteActionPerformed
        // TODO add your handling code here:
        
        TelaCadastroCliente telaCadCliente = new TelaCadastroCliente();
        painelPrincipal.add(telaCadCliente);
        telaCadCliente.setVisible(true);
        
        
    }//GEN-LAST:event_itemAddClienteActionPerformed

    private void abrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCaixaActionPerformed
        Date horario = new Date();
        Caixa c = new Caixa(1, horario, horario, 0);
        try {
            Banco.abrir();
            String count = "SELECT count(*) as contador from controleCaixa where status = 1;";
            PreparedStatement pst = Banco.getConexao().prepareStatement(count);
            ResultSet rs = pst.executeQuery();
            rs.next();
            int alo = rs.getInt("contador");
            if (alo == 0)
                caixa.inserir(c);
            else
                JOptionPane.showMessageDialog(null, "Caixa já está aberto");
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_abrirCaixaActionPerformed

    private void itemAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddMedActionPerformed
        // TODO add your handling code here:
        TelaCadastroMedicamento telaCadMedicamento = new TelaCadastroMedicamento();
        painelPrincipal.add(telaCadMedicamento);
        telaCadMedicamento.setVisible(true);
    }//GEN-LAST:event_itemAddMedActionPerformed

    private void fecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharCaixaActionPerformed
        Date horario = new Date();
        Caixa c = new Caixa(1, horario, horario, 0);
        try {
            Banco.abrir();
            String count = "SELECT count(*) as contador from controleCaixa where status = 1;";
            PreparedStatement pst = Banco.getConexao().prepareStatement(count);
            ResultSet rs = pst.executeQuery();
            rs.next();
            int alo = rs.getInt("contador");
            if (alo == 1)
                caixa.inserir(c);
            else
                JOptionPane.showMessageDialog(null, "Caixa já está fechado");
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_fecharCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirCaixa;
    private javax.swing.JMenuItem fecharCaixa;
    private javax.swing.JMenuItem itemAddCliente;
    private javax.swing.JMenuItem itemAddMed;
    private javax.swing.JMenuItem itemAltCliente;
    private javax.swing.JMenuItem itemConsultaCliente;
    private javax.swing.JMenuItem itemExcluirCliente;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenu menuCaixa;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
